"""
Utility modules for the Mock Web3 Wallet backend.
"""

from .database import (
    DatabaseConnection,
    get_db_connection,
    get_db_cursor,
    test_connection
)
from .crypto_manager import CryptoManager
from .exceptions import (
    WalletException,
    AuthenticationError,
    InvalidPasswordError,
    WalletLockedError,
    SessionExpiredError,
    UnauthorizedError,
    ValidationError,
    InvalidAddressError,
    InvalidAmountError,
    InvalidMnemonicError,
    InsufficientBalanceError,
    InvalidPhoneNumberError,
    TransactionError,
    ApprovalExpiredError,
    InvalidSignatureError,
    PriceToleranceExceededError,
    ApprovalNotFoundError,
    TransactionFailedError,
    ResourceNotFoundError,
    WalletNotFoundError,
    AccountNotFoundError,
    TransactionNotFoundError,
    DatabaseError,
    DatabaseConnectionError,
    DatabaseConstraintError,
    DuplicateResourceError,
    CryptoError,
    DecryptionError,
    EncryptionError,
    KeyDerivationError,
    ExternalServiceError,
    SkipAPIError,
    NotificationError
)

__all__ = [
    'DatabaseConnection',
    'get_db_connection',
    'get_db_cursor',
    'test_connection',
    'CryptoManager',
    'WalletException',
    'AuthenticationError',
    'InvalidPasswordError',
    'WalletLockedError',
    'SessionExpiredError',
    'UnauthorizedError',
    'ValidationError',
    'InvalidAddressError',
    'InvalidAmountError',
    'InvalidMnemonicError',
    'InsufficientBalanceError',
    'InvalidPhoneNumberError',
    'TransactionError',
    'ApprovalExpiredError',
    'InvalidSignatureError',
    'PriceToleranceExceededError',
    'ApprovalNotFoundError',
    'TransactionFailedError',
    'ResourceNotFoundError',
    'WalletNotFoundError',
    'AccountNotFoundError',
    'TransactionNotFoundError',
    'DatabaseError',
    'DatabaseConnectionError',
    'DatabaseConstraintError',
    'DuplicateResourceError',
    'CryptoError',
    'DecryptionError',
    'EncryptionError',
    'KeyDerivationError',
    'ExternalServiceError',
    'SkipAPIError',
    'NotificationError'
]
